### ISSUE TITLE
Stereo Vision using OpenCV on Buildroot

### ISSUE THREAD

**Issue by SwathiVenkatachalam** [KapureCUB/final-project-assignment-KapureCUB#11]
Code algorithm for stereo vision application

DoD: Test output depth map of object from camera

Blockers: None so far.

Completed: [Commit](https://github.com/cu-ecen-aeld/final-project-SwathiVenkatachalam/commit/fb9f0d00727974a77eb5492219056b38d1199863)

**Comment by KapureCUB** [comment]
Output depth map image is stored in client RPi as shown as are the left and right rectified images from the 2 cameras.

![Image](https://github.com/KapureCUB/final-project-assignment-KapureCUB/assets/143363823/106db921-b96a-450b-94e8-583995b14553)
