### ISSUE TITLE
OpenCV Setup

### ISSUE THREAD

**Issue by SwathiVenkatachalam** [KapureCUB/final-project-assignment-KapureCUB#6]
Initial OpenCV Setup

DoD:

- [x] Download necessary image processing libraries
- [x] Figuring out the camera configuration parameters
- [x] Image capture using camera

Blockers: None so far
Completed: OpenCV Setup 
[Commit](https://github.com/cu-ecen-aeld/final-project-KapureCUB/commit/21ab411ad5a275298f67d7fc5048d34d7690d209)

**Comment by KapureCUB** [comment]
The following libraries and packages are needed for stereo camera system
- numpy
- OpenCV-python
- OpenCV-python-headless

The process for depth estimation is as follows 
1. Performing the intrinsic and extrinsic parameters for camera - this is done by providing a checkered pattern image captured by the camera and calling findChessboardCorners() function. This performs the necessary corner detection and finds out the intrinsic matrix K. Refer the document [here](https://learnopencv.com/camera-calibration-using-opencv/).
2. Rectification of the image - Image rectification is essentially to create a flat comparable image from a camera after removing the distortion effects. 
3. Performing block matching for depth map - the openCV algorithms perform the optimum block matching algorithms to estimate the skewness in the provided images and using the camera parameters estimate the depth of the image.

Progress so far: 
- Using python for developing the user space application as the support and resources for opencv using python is abundant and time saving.
- camera parameters are obtained using a demo checkerboard image captured from the c270 and is statically fed to the code for calibrating the camera parameters. Below code snippet from the git repo is specifying the calibration step where  findChessboardCorners() function is used.
![Code for intrinsic parameters](https://github.com/KapureCUB/final-project-assignment-KapureCUB/assets/143363823/60ef283b-c70f-437d-a4c9-65a6a96d11bf)
- the below checkerboard image was captured from the camera 
![Image](https://github.com/KapureCUB/final-project-assignment-KapureCUB/assets/143363823/3847d4b2-b37f-4146-8054-de3fe2c04b45)
- work is in progress to validate the parameters obtained

**Comment by KapureCUB** [comment]
The final commit can be found [here](https://github.com/cu-ecen-aeld/final-project-KapureCUB/commit/21ab411ad5a275298f67d7fc5048d34d7690d209).
