### ISSUE TITLE
Camera calibration and image rectification

### ISSUE THREAD

**Issue by SwathiVenkatachalam** [KapureCUB/final-project-assignment-KapureCUB#8]
DoD:

- [x] Calculate camera Q matrix
- [x] Perform image gray scaling and obtain rectified image
- [x] Get a static depth map based on sample images

Blockers: As we have only 2 cameras, one of which is used by Swathi for camera driver, the real time capture could not be tested. Will be tested in the next sprint along with socket implementation

**Comment by KapureCUB** [comment]
1. Q matrix calculation and corner detection: 
Below images show the captured images for the corner detection performed for calculation camera calibration parameters. The algorithm successfully detects corners even at inclined angles as evident from second image.

The calibrated camera matrix is 
 [[1.24658345e+03 0.00000000e+00 6.44698034e+02]
 [0.00000000e+00 1.24438489e+03 3.50116318e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]

![Image](https://github.com/KapureCUB/final-project-assignment-KapureCUB/assets/143363823/62c6686e-11df-492e-91ba-e1d4fe5860f4)
![Image](https://github.com/KapureCUB/final-project-assignment-KapureCUB/assets/143363823/ed077de5-6d89-4980-a384-d278143d1440)

2. Rectified Grayscale images: 
The next step was to align the c and y axis of the images. Below is the result generated for the static images fed as samples.
First is the left image while next is the right image. A disparity maybe seen in the images but the axes error are cleared. Refer original images in the git repo for comparison.



![Image](https://github.com/KapureCUB/final-project-assignment-KapureCUB/assets/143363823/bbb89306-9c77-41f4-85b9-bc83c587ecdb)
![Image](https://github.com/KapureCUB/final-project-assignment-KapureCUB/assets/143363823/4061546e-b2e3-4df9-8735-5a6fee27374f)


3. Depth Map:
Below is the result of the static images shown above. the Depth regions are still a bit unclear and disparity and blocksize variation are not generation a defined results yet. But as the images are approximated by using only one camera and moving it to get these images, these images issues will be solved when both cameras are actually used for capturing in real-time. The below result is at disparity value of 80 and block size of 9.


![Image](https://github.com/KapureCUB/final-project-assignment-KapureCUB/assets/143363823/07d43a70-56cb-43bb-9c49-b68d45f470a8)

**Comment by KapureCUB** [comment]
The final commit can be found [here](https://github.com/cu-ecen-aeld/final-project-KapureCUB/commit/71fbaa4fd77e3f128ada08662bd811b9bcdabb77).
