### ISSUE TITLE
Image capture as buffer in userspace

### ISSUE THREAD

**Issue by SwathiVenkatachalam** [KapureCUB/final-project-assignment-KapureCUB#9]
DoD:

- [x] Capture image buffer in userspace

Blockers: As the camera driver is not implemented during this sprint task, a current USB driver was taken and whether the image buffer is received is check. Full implementation to be done in sprint 3

**Comment by KapureCUB** [comment]
The buffer is as below which was received in userspace. The result is truncated in output for display purposes


![Image](https://github.com/KapureCUB/final-project-assignment-KapureCUB/assets/143363823/2c131038-4dae-469b-a13d-5125143a6f29)

**Comment by KapureCUB** [comment]
The final commit can be found [here](https://github.com/cu-ecen-aeld/final-project-KapureCUB/commit/71fbaa4fd77e3f128ada08662bd811b9bcdabb77).
